# Based on https://github.com/Jorge-C/ordination/blob/master/.travis.yml
language: python
python:
  - "2.7"
notifications:
  email: false
# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  # Update conda itself
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
# Test with and without netCDF4/scipy/pydap
env:
  - UPDATE_PYENV='conda remove --yes scipy netCDF4'
  - UPDATE_PYENV='pip install pydap'
# Install packages
install:
  - conda create --yes -n test_env python=$TRAVIS_PYTHON_VERSION pip nose mock numpy pandas scipy netCDF4
  - source activate test_env
  - echo $UPDATE_PYENV; $UPDATE_PYENV
  - python setup.py install
# Run test
script:
  - nosetests
